# Ubuntu 20.04 image with CUDA + OpenGL and ROS Noetic
# Per suggestion from the below post, if graphics and GPU acceleration support is needed then do not start with the OSRF ROS Docker image/
# Instead, start with the NVIDIA Docker Hub image. This is because, as we all know, getting NVIDIA drivers working is a huge pain, so it's easier to get ROS working with NVIDIA rather than the other way around.
# https://roboticseabass.com/2021/04/21/docker-and-ros/
FROM nvidia/cudagl:11.1.1-base-ubuntu20.04

# Install basic apt packages
RUN apt-get update && apt-get install -y locales lsb-release

# Set up locale and UTF-8 encoding so setup runs without errors
ARG DEBIAN_FRONTEND=noninteractive
RUN dpkg-reconfigure locales

# Install ROS Noetic
RUN sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
RUN apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
RUN apt-get update \
 && apt-get install -y --no-install-recommends ros-noetic-desktop-full
RUN apt-get install -y --no-install-recommends python3-rosdep
RUN rosdep init \
 && rosdep fix-permissions \
 && rosdep update
RUN echo "source /opt/ros/noetic/setup.bash" >> ~/.bashrc

# Install basic apt packages
RUN apt-get update && apt-get install -y \
  vim \
  cmake \
  g++ \
  git \
  gnupg gnupg1 gnupg2 \
  libcanberra-gtk* \
  python3-catkin-tools \
  python3-pip \
  python3-tk \
  wget
  
# Install additional ROS packages
RUN apt-get install -y \
  ros-noetic-gmapping \
  ros-noetic-navigation \
  ros-noetic-py-trees \
  ros-noetic-py-trees-ros

